### ISSUE TITLE
import fails

### ISSUE THREAD

**Issue by vitamins** [sfu-db/dataprep#298]
**To Reproduce**
1. Install dataprep on Windows 10 using
`py -m pip install dataprep`
2. Run the first line in the introduction

```
>>> from dataprep.eda import plot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python38\lib\site-packages\dataprep\eda\__init__.py", line 8, in <module>
    from .distribution import compute, plot, render
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python38\lib\site-packages\dataprep\eda\distribution\__init__.py", line 13, in <module>
    from ..report import Report
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python38\lib\site-packages\dataprep\eda\report.py", line 15, in <module>
    from IPython.display import HTML, display
ModuleNotFoundError: No module named 'IPython'
```

**Desktop:**
 - OS: Windows 10
 - Platform: Windows Powershell
 - Platform Version [e.g. 1.0]
 - Python Version Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32
 - Dataprep Version: dataprep-0.2.11-py3-none-any.whl

**Additional context**
```
 py -m pip install dataprep
Collecting dataprep
  Downloading dataprep-0.2.11-py3-none-any.whl (95 kB)
     |████████████████████████████████| 95 kB 3.3 MB/s
Requirement already satisfied: pillow<8.0.0,>=7.1.2 in c:\users\lukas\appdata\local\programs\python\python38\lib\site-packages (from dataprep) (7.2.0)
Collecting requests<2.24,>=2.23
  Downloading requests-2.23.0-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB ...
Collecting jinja2<2.12,>=2.11
  Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 6.4 MB/s
Collecting lxml<4.6,>=4.5
  Downloading lxml-4.5.2-cp38-cp38-win_amd64.whl (3.5 MB)
     |████████████████████████████████| 3.5 MB 6.4 MB/s
Collecting aiohttp<4.0.0,>=3.6.2
  Downloading aiohttp-3.6.2-py3-none-any.whl (441 kB)
     |████████████████████████████████| 441 kB 2.2 MB/s
Collecting dask[complete]<2.23,>=2.22
  Downloading dask-2.22.0-py3-none-any.whl (828 kB)
     |████████████████████████████████| 828 kB 3.2 MB/s
Collecting jsonschema<3.3,>=3.2
  Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 3.8 MB/s
Collecting numpy<1.19,>=1.18
  Downloading numpy-1.18.5-cp38-cp38-win_amd64.whl (12.8 MB)
     |████████████████████████████████| 12.8 MB 3.2 MB/s
Collecting tornado==5.0.2
  Downloading tornado-5.0.2.tar.gz (506 kB)
     |████████████████████████████████| 506 kB 3.2 MB/s
Collecting wordcloud<2.0.0,>=1.7.0
  Downloading wordcloud-1.8.0-cp38-cp38-win_amd64.whl (159 kB)
     |████████████████████████████████| 159 kB 3.3 MB/s
Collecting nltk<4.0,>=3.5
  Downloading nltk-3.5.zip (1.4 MB)
     |████████████████████████████████| 1.4 MB 3.2 MB/s
Collecting tqdm<5.0.0,>=4.47.0
  Downloading tqdm-4.48.2-py2.py3-none-any.whl (68 kB)
     |████████████████████████████████| 68 kB 2.3 MB/s
Collecting bokeh<2.1,>=2.0
  Downloading bokeh-2.0.2.tar.gz (8.6 MB)
     |████████████████████████████████| 8.6 MB 2.2 MB/s
Collecting scipy<1.5,>=1.4
  Downloading scipy-1.4.1-cp38-cp38-win_amd64.whl (31.0 MB)
     |████████████████████████████████| 31.0 MB 2.2 MB/s
Collecting jsonpath-ng<2.0.0,>=1.5.1
  Downloading jsonpath-ng-1.5.1.tar.gz (30 kB)
Collecting pandas<1.1,>=1.0
  Downloading pandas-1.0.5-cp38-cp38-win_amd64.whl (8.9 MB)
     |████████████████████████████████| 8.9 MB 1.7 MB/s
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\lukas\appdata\local\programs\python\python38\lib\site-packages\chardet-3.0.4-py3.8.egg (from requests<2.24,>=2.23->dataprep) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in c:\users\lukas\appdata\local\programs\python\python38\lib\site-packages\idna-2.10-py3.8.egg (from requests<2.24,>=2.23->dataprep) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lukas\appdata\local\programs\python\python38\lib\site-packages\certifi-2020.6.20-py3.8.egg (from requests<2.24,>=2.23->dataprep) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\lukas\appdata\local\programs\python\python38\lib\site-packages\urllib3-1.25.9-py3.8.egg (from requests<2.24,>=2.23->dataprep) (1.25.9)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\lukas\appdata\local\programs\python\python38\lib\site-packages (from jinja2<2.12,>=2.11->dataprep) (1.1.1)
Collecting multidict<5.0,>=4.5
  Downloading multidict-4.7.6-cp38-cp38-win_amd64.whl (48 kB)
     |████████████████████████████████| 48 kB 1.4 MB/s
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.5.1-cp38-cp38-win_amd64.whl (128 kB)
     |████████████████████████████████| 128 kB 3.2 MB/s
Collecting async-timeout<4.0,>=3.0
  Downloading async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Collecting attrs>=17.3.0
  Downloading attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting pyyaml
  Downloading PyYAML-5.3.1-cp38-cp38-win_amd64.whl (219 kB)
     |████████████████████████████████| 219 kB 2.2 MB/s
Collecting partd>=0.3.10; extra == "complete"
  Downloading partd-1.1.0-py3-none-any.whl (19 kB)
Collecting toolz>=0.8.2; extra == "complete"
  Downloading toolz-0.10.0.tar.gz (49 kB)
     |████████████████████████████████| 49 kB 3.2 MB/s
Collecting fsspec>=0.6.0; extra == "complete"
  Downloading fsspec-0.8.0-py3-none-any.whl (85 kB)
     |████████████████████████████████| 85 kB 3.0 MB/s
Collecting cloudpickle>=0.2.2; extra == "complete"
  Downloading cloudpickle-1.5.0-py3-none-any.whl (22 kB)
Collecting distributed>=2.0; extra == "complete"
  Downloading distributed-2.23.0-py3-none-any.whl (650 kB)
     |████████████████████████████████| 650 kB 2.2 MB/s
Requirement already satisfied: setuptools in c:\users\lukas\appdata\local\programs\python\python38\lib\site-packages (from jsonschema<3.3,>=3.2->dataprep) (41.2.0)
Requirement already satisfied: six>=1.11.0 in c:\users\lukas\appdata\local\programs\python\python38\lib\site-packages (from jsonschema<3.3,>=3.2->dataprep) (1.15.0)
Collecting pyrsistent>=0.14.0
  Downloading pyrsistent-0.16.0.tar.gz (108 kB)
     |████████████████████████████████| 108 kB 3.2 MB/s
Requirement already satisfied: matplotlib in c:\users\lukas\appdata\local\programs\python\python38\lib\site-packages (from wordcloud<2.0.0,>=1.7.0->dataprep) (3.3.0)
Collecting click
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 3.0 MB/s
Collecting joblib
  Downloading joblib-0.16.0-py3-none-any.whl (300 kB)
     |████████████████████████████████| 300 kB 3.3 MB/s
Collecting regex
  Downloading regex-2020.7.14-cp38-cp38-win_amd64.whl (264 kB)
     |████████████████████████████████| 264 kB 3.3 MB/s
Requirement already satisfied: python-dateutil>=2.1 in c:\users\lukas\appdata\local\programs\python\python38\lib\site-packages (from bokeh<2.1,>=2.0->dataprep) (2.8.1)
Collecting packaging>=16.8
  Downloading packaging-20.4-py2.py3-none-any.whl (37 kB)
Collecting typing_extensions>=3.7.4
  Downloading typing_extensions-3.7.4.2-py3-none-any.whl (22 kB)
Collecting ply
  Downloading ply-3.11-py2.py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 3.2 MB/s
Collecting decorator
  Downloading decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Requirement already satisfied: pytz>=2017.2 in c:\users\lukas\appdata\local\programs\python\python38\lib\site-packages (from pandas<1.1,>=1.0->dataprep) (2020.1)
Collecting locket
  Downloading locket-0.2.0.tar.gz (3.5 kB)
Collecting msgpack>=0.6.0
  Downloading msgpack-1.0.0-cp38-cp38-win_amd64.whl (73 kB)
     |████████████████████████████████| 73 kB 2.6 MB/s
Collecting zict>=0.1.3
  Downloading zict-2.0.0-py3-none-any.whl (10 kB)
Collecting psutil>=5.0
  Downloading psutil-5.7.2-cp38-cp38-win_amd64.whl (243 kB)
     |████████████████████████████████| 243 kB 3.3 MB/s
Collecting tblib>=1.6.0
  Downloading tblib-1.7.0-py2.py3-none-any.whl (12 kB)
Collecting sortedcontainers!=2.0.0,!=2.0.1
  Downloading sortedcontainers-2.2.2-py2.py3-none-any.whl (29 kB)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\lukas\appdata\local\programs\python\python38\lib\site-packages (from matplotlib->wordcloud<2.0.0,>=1.7.0->dataprep) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\lukas\appdata\local\programs\python\python38\lib\site-packages (from matplotlib->wordcloud<2.0.0,>=1.7.0->dataprep) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\lukas\appdata\local\programs\python\python38\lib\site-packages (from matplotlib->wordcloud<2.0.0,>=1.7.0->dataprep) (0.10.0)
Collecting heapdict
  Downloading HeapDict-1.0.1-py3-none-any.whl (3.9 kB)
Using legacy setup.py install for tornado, since package 'wheel' is not installed.
Using legacy setup.py install for nltk, since package 'wheel' is not installed.
Using legacy setup.py install for bokeh, since package 'wheel' is not installed.
Using legacy setup.py install for jsonpath-ng, since package 'wheel' is not installed.
Using legacy setup.py install for toolz, since package 'wheel' is not installed.
Using legacy setup.py install for pyrsistent, since package 'wheel' is not installed.
Using legacy setup.py install for locket, since package 'wheel' is not installed.
ERROR: distributed 2.23.0 has requirement tornado>=6.0.3; python_version >= "3.8", but you'll have tornado 5.0.2 which is incompatible.
Installing collected packages: requests, jinja2, lxml, multidict, yarl, async-timeout, attrs, aiohttp, pyyaml, locket, toolz, partd, fsspec, cloudpickle, msgpack, heapdict, zict, psutil, tornado, click, tblib, sortedcontainers, distributed, numpy, pandas, packaging, typing-extensions, bokeh, dask, pyrsistent, jsonschema, wordcloud, joblib, regex, tqdm, nltk, scipy, ply, decorator, jsonpath-ng, dataprep
  Attempting uninstall: requests
    Found existing installation: requests 2.24.0
    Uninstalling requests-2.24.0:
      Successfully uninstalled requests-2.24.0
    Running setup.py install for locket ... done
    Running setup.py install for toolz ... done
    Running setup.py install for tornado ... done
  WARNING: The scripts dask-scheduler.exe, dask-ssh.exe and dask-worker.exe are installed in 'C:\Users\Lukas\AppData\Local\Programs\Python\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.0
    Uninstalling numpy-1.19.0:
      Successfully uninstalled numpy-1.19.0
  WARNING: The script f2py.exe is installed in 'C:\Users\Lukas\AppData\Local\Programs\Python\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Attempting uninstall: pandas
    Found existing installation: pandas 1.1.0
    Uninstalling pandas-1.1.0:
      Successfully uninstalled pandas-1.1.0
    Running setup.py install for bokeh ... done
    Running setup.py install for pyrsistent ... done
  WARNING: The script jsonschema.exe is installed in 'C:\Users\Lukas\AppData\Local\Programs\Python\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script wordcloud_cli.exe is installed in 'C:\Users\Lukas\AppData\Local\Programs\Python\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script tqdm.exe is installed in 'C:\Users\Lukas\AppData\Local\Programs\Python\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
    Running setup.py install for nltk ... done
  Attempting uninstall: scipy
    Found existing installation: scipy 1.5.2
    Uninstalling scipy-1.5.2:
      Successfully uninstalled scipy-1.5.2
    Running setup.py install for jsonpath-ng ... done
Successfully installed aiohttp-3.6.2 async-timeout-3.0.1 attrs-19.3.0 bokeh-2.0.2 click-7.1.2 cloudpickle-1.5.0 dask-2.22.0 dataprep-0.2.11 decorator-4.4.2 distributed-2.23.0 fsspec-0.8.0 heapdict-1.0.1 jinja2-2.11.2 joblib-0.16.0 jsonpath-ng-1.5.1 jsonschema-3.2.0 locket-0.2.0 lxml-4.5.2 msgpack-1.0.0 multidict-4.7.6 nltk-3.5 numpy-1.18.5 packaging-20.4 pandas-1.0.5 partd-1.1.0 ply-3.11 psutil-5.7.2 pyrsistent-0.16.0 pyyaml-5.3.1 regex-2020.7.14 requests-2.23.0 scipy-1.4.1 sortedcontainers-2.2.2 tblib-1.7.0 toolz-0.10.0 tornado-5.0.2 tqdm-4.48.2 typing-extensions-3.7.4.2 wordcloud-1.8.0 yarl-1.5.1 zict-2.0.0
WARNING: You are using pip version 20.1.1; however, version 20.2.2 is available.
You should consider upgrading via the 'C:\Users\Lukas\AppData\Local\Programs\Python\Python38\python.exe -m pip install --upgrade pip' command.
```

**Comment by dovahcrow** [comment]
Hi @vitamins, we've already been aware of this issue and it is fixed in commit 75542cda64570f1fe3c4ac61e670cc0ce2febaa3.
