### ISSUE TITLE
Cryptic error message when a column contains only NaN

### ISSUE THREAD

**Issue by vitamins** [sfu-db/dataprep#299]
**Describe the bug**
When a column of the dataframe passed to plot contains only NaNs, a cryptic error message is shown.

**To Reproduce**
```
nan_value = float("NaN")
>>> df = pd.DataFrame(5 * [[1, nan_value]]
... )
>>> df
   0   1
0  1 NaN
1  1 NaN
2  1 NaN
3  1 NaN
4  1 NaN
>>> rep = plot(df)
C:\Users\Lukas\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\lib\histograms.py:433: RuntimeWarning: invalid value encountered in greater
  if np.any(bin_edges[:-1] > bin_edges[1:]):
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python38\lib\site-packages\dataprep\eda\distribution\__init__.py", line 165, in plot
    figure = render(intermediate, yscale=yscale, tile_size=tile_size)
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python38\lib\site-packages\dataprep\eda\distribution\render.py", line 1920, in render
    visual_elem = render_distribution_grid(
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python38\lib\site-packages\dataprep\eda\distribution\render.py", line 1565, in render_distribution_grid
    fig = hist_viz(data, nrows, col, yscale, plot_width, plot_height, False)
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python38\lib\site-packages\dataprep\eda\distribution\render.py", line 441, in hist_viz
    fig = Figure(
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python38\lib\site-packages\bokeh\plotting\figure.py", line 155, in __init__
    super().__init__(*arg, **kw)
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python38\lib\site-packages\bokeh\model.py", line 234, in __init__
    super().__init__(**kwargs)
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python38\lib\site-packages\bokeh\core\has_props.py", line 247, in __init__
    setattr(self, name, value)
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python38\lib\site-packages\bokeh\core\has_props.py", line 274, in __setattr__
    super().__setattr__(name, value)
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python38\lib\site-packages\bokeh\core\property\descriptors.py", line 539, in __set__
    self._internal_set(obj, value, setter=setter)
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python38\lib\site-packages\bokeh\core\property\descriptors.py", line 760, in _internal_set
    value = self.property.prepare_value(obj, self.name, value)
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python38\lib\site-packages\bokeh\core\property\bases.py", line 331, in prepare_value
    raise e
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python38\lib\site-packages\bokeh\core\property\bases.py", line 324, in prepare_value
    self.validate(value)
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python38\lib\site-packages\bokeh\core\property\instance.py", line 112, in validate
    raise ValueError(msg)
ValueError: expected an instance of type Title, got 0 of type int
```

**Expected behavior**
A clear and concise description of the error is shown.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Platform Powershell
 - Python Version Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32
 - Dataprep Version dataprep-0.2.11-py3-none-any.whl

**Additional context**
invalid value encountered in bug report

**Comment by brandonlockhart** [comment]
Hi @vitamins. Thanks for raising this issue! This is fixed in PR #316 by creating an empty plot if a column contains only nan:
![Screen Shot 2020-09-01 at 10 54 53 PM](https://user-images.githubusercontent.com/25874021/91937812-9c0cce80-eca7-11ea-802e-17cb389c79dd.png)
