### ISSUE TITLE
If the original dataframe is constructed using Dask.Dataframe, then Create_report throws error ( saying it found delayed ). Looks like the code doesn't compute for DaskFrame

### ISSUE THREAD

**Issue by ssenathi** [sfu-db/dataprep#332]
**Need Dask Dataframe support  for Create_REPORT - Need to materialize computes**
When the input dataframe is constructed from Dask.DataFrame , create_report(df) throws error
 "Missing Cells": float(ncells - npresent_cells),
TypeError: float() argument must be a string or a number, not 'Delayed'

**To Reproduce**
1. Construct Dataframe using Dask dataframe ( dd.read_csv(...)  dd.compute())
2. call create_report(df)
3. See error

**Expected behavior**
create_report runs successfully

**Screenshots**
Formating Overview:  11%|███████▎                                                        | 4/35 [00:35<04:36,  8.93s/it]Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ssenathi/.local/lib/python3.6/site-packages/dataprep/eda/create_report/__init__.py", line 51, in create_report
    "components": format_report(df, mode),
  File "/home/ssenathi/.local/lib/python3.6/site-packages/dataprep/eda/create_report/formatter.py", line 49, in format_report
    comps = format_basic(df, comps)
  File "/home/ssenathi/.local/lib/python3.6/site-packages/dataprep/eda/create_report/formatter.py", line 136, in format_basic
    comps["overview"] = _format_stats(stats, "overview")
  File "/home/ssenathi/.local/lib/python3.6/site-packages/dataprep/eda/create_report/formatter.py", line 297, in _format_stats
    "Missing Cells": float(ncells - npresent_cells),
TypeError: float() argument must be a string or a number, not 'Delayed'

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser : chrome
 - Platform  Jupyter Lab,
 - Dataprep Version [ 0.2.2]

**Additional context**

**Comment by ssenathi** [comment]
also. Dask Dataframe works fine with Plot.

**Comment by brandonlockhart** [comment]
Hi @ssenathi, our last released version only supports Pandas dataframes. `create_report` on the develop branch supports Dask dataframes, and will be available in the next release. You could try using the develop branch with `pip install git+https://github.com/sfu-db/dataprep.git@develop`
