### ISSUE TITLE
NumExpr

### ISSUE THREAD

**Issue by bbarclay** [sfu-db/dataprep#770]
Getting this bug. Have tried in multiple situations. 

Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/brandon/opt/anaconda3/lib/python3.9/site-packages/dataprep/eda/__init__.py", line 8, in <module>
    from .create_report import create_report
  File "/Users/brandon/opt/anaconda3/lib/python3.9/site-packages/dataprep/eda/create_report/__init__.py", line 10, in <module>
    from .formatter import format_report
  File "/Users/brandon/opt/anaconda3/lib/python3.9/site-packages/dataprep/eda/create_report/formatter.py", line 17, in <module>
    from ..distribution import render
  File "/Users/brandon/opt/anaconda3/lib/python3.9/site-packages/dataprep/eda/distribution/__init__.py", line 13, in <module>
    from .compute import compute
  File "/Users/brandon/opt/anaconda3/lib/python3.9/site-packages/dataprep/eda/distribution/compute/__init__.py", line 14, in <module>
    from .univariate import compute_univariate
  File "/Users/brandon/opt/anaconda3/lib/python3.9/site-packages/dataprep/eda/distribution/compute/univariate.py", line 11, in <module>
    from nltk.stem import PorterStemmer, WordNetLemmatizer
  File "/Users/brandon/opt/anaconda3/lib/python3.9/site-packages/nltk/__init__.py", line 137, in <module>
    from nltk.text import *
  File "/Users/brandon/opt/anaconda3/lib/python3.9/site-packages/nltk/text.py", line 29, in <module>
    from nltk.tokenize import sent_tokenize
  File "/Users/brandon/opt/anaconda3/lib/python3.9/site-packages/nltk/tokenize/__init__.py", line 65, in <module>
    from nltk.tokenize.casual import TweetTokenizer, casual_tokenize
  File "/Users/brandon/opt/anaconda3/lib/python3.9/site-packages/nltk/tokenize/casual.py", line 272, in <module>
    class TweetTokenizer:
  File "/Users/brandon/opt/anaconda3/lib/python3.9/site-packages/nltk/tokenize/casual.py", line 357, in TweetTokenizer
    def WORD_RE(self) -> regex.Pattern:
AttributeError: module 'regex' has no attribute 'Pattern'

**Comment by moreaupascal56** [comment]
Hello, wouldn't it be the same error as here : [https://stackoverflow.com/questions/69405949/attributeerror-module-regex-has-no-attribute-pattern](https://stackoverflow.com/questions/69405949/attributeerror-module-regex-has-no-attribute-pattern) and an issue with nltk? 
Regards 😄

**Comment by jinglinpeng** [comment]
Hi @moreaupascal56 , thanks for the replying.
Hi @bbarclay , thanks for the issue. It looks an NLTK version issue as discussed in #705 . Could you try a lower version of NLTK?
